myforth/apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
	path('', views.index, name = 'index'), 
	path('<int:article_id>/', views.detail, name = 'detail'), 
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'), 
	

]

myforth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [    
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),    
]

myforth/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone


class Article(models.Model):
	article_title = models.CharField('title of article', max_length = 200)
	article_text = models.TextField('text of article')
	pub_date = models.DateTimeField('date of publication')


	def __str__(self):
		return self.article_title


	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('author of comment', max_length = 50)
	comment_text = models.CharField('text of comment', max_length = 200)


	def __str__(self):
		return self.author_name

myforth/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article
from django.urls import reverse


def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5] 
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
	try:
		a = Article.objects.get(id = article_id)

	except:
		raise Http404('Article not found!')

	latest_comments_list = a.comment_set.order_by('-id')[:10]

	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
	try:
		a = Article.objects.get(id = article_id)

	except:
		raise Http404('Article not found!')

	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

	return HttpResponseRedirect(reverse('articles:detail', args = (a.id,)))

myforth/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

	<h2>{{article.article_title}}</h2>

	<p>{{article.article_text}}</p>

	<em>{{article.pub_date}}</em>

	{% if article.was_published_recently %}
		NEW article!
	{% endif %}

	<hr>

	{% if latest_comments_list %}
		{% for c in latest_comments_list %}
			<p>
				<strong>{{c.author_name}}</strong>
				<p>{{c.comment_text}}</p>
			</p>
		{% endfor %}
	{% else %}
		Comments not found! Be the first!
	{% endif %}

	<hr>

	<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

		{% csrf_token %}

		<input type="text" required placeholder="Your name" name="name"><br>
		<textarea name="text" required placeholder="Comment text" cols="30" rows="10"></textarea>
		<br>

		<button type="submit">Leave comment</button>

	</form>

{% endblock %}

myforth/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Recent Articles{% endblock %}

{% block content %}

	{% if latest_articles_list %}
		{% for a in latest_articles_list %}
			<h3><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h3>
		{% endfor %}

	{% else %}
		Articles not found.
	{% endif %}

{% endblock %}

myforth/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}My blog{% endblock %}</title>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>